<?php
namespace Dfe\Qiwi;
use Df\Payment\Source\Identification;
/**
 * 2017-09-03
 * @method Method m()
 * @method Settings s()
 */
final class Charge extends \Df\Payment\Charge {
	/**
	 * 2017-09-04 Our local (without the module prefix) internal payment ID.
	 * @override
	 * @see \Df\Payment\Operation::id()
	 * @used-by pRedirect()
	 * @used-by \Dfe\Qiwi\Init\Action::transId()
	 * @return string
	 */
	function id() {return dfc($this, function() {return Identification::get($this->o());});}

	/**
	 * 2017-09-04
	 * @used-by \Dfe\Qiwi\Init\Action::req()
	 * @return array(string, array(string => mixed))
	 */
	function pBill() {$s = $this->s(); return [

	];}

	/**
	 * 2017-09-04
	 * @used-by \Dfe\Qiwi\Init\Action::req()
	 * @return array(string, array(string => mixed))
	 */
	function pRedirect() {$s = $this->s(); return [
		// 2017-09-04
		// «The URL to which the payer will be redirected
		// when creation of Visa QIWI Wallet transaction is unsuccessful.
		// URL must be within merchant's site.»
		// «URL для переадресации в случае неуспеха при создании транзакции в Visa QIWI Wallet.
		// Ссылка должна вести на сайт провайдера.
		// Если пользователь выбрал на платежной форме способ оплаты,
		// отличный от оплаты с баланса Visa QIWI Wallet,
		// то переадресация на сайт провайдера не выполняется.»
		// Optional, string.
		'failUrl' => $this->customerReturnRemoteWithFailure()
		// 2017-09-04
		// «This parameter (if true) means that invoice page would be opened in "iframe".
		// The checkout page appears more compact
		// and can be embedded conveniently within the merchant’s site.
		// Default value is false.»
		// «Признак отображения страницы в iframe
		// (более компактный вид, удобный для встраивания ее в сайт провайдера).
		// По умолчанию false»
		// Optional, true/false.
		,'iframe' => false
		// 2017-09-04
		// «Accepts mobile, qw, card, wm, ssk.
		// Default payment method to show first for the client.
		// Allowed values:
		// 		card – a credit/debit card;
		// 		mobile – client’s cell phone account;
		// 		qw – Visa QIWI Wallet account;
		// 		ssk – payment by cash in a QIWI Terminal;
		// 		wm – linked WebMoney wallet.
		// When specified method is inaccessible for the Customer,
		// the page contains notice about it and the client can choose another method.»
		// «Способ оплаты по умолчанию,
		// который необходимо отобразить пользователю при открытии платежной формы.
		// Возможные значения:
		// 		card – оплата банковской картой;
		// 		mobile – оплата с баланса мобильного телефона;
		// 		qw – оплата с баланса Visa QIWI Wallet;
		// 		ssk – оплата наличными в терминале QIWI;
		// 		wm – оплата с привязанного кошелька WebMoney.
		// Если способ оплаты не доступен, пользователю отображается предупреждение,
		// при этом на странице можно выбрать другие способы оплаты.»
		// Optional, string.
		,'pay_source' => ''
		// 2017-09-04
		// «Merchant’s ID in Visa QIWI Wallet system,
		// corresponds to {prv_id} parameter used to create the bill.»
		// «Идентификатор провайдера.
		// Соответствует параметру {prv_id} из запроса на выставление счета.»
		// Required, string.
		,'shop' => $s->merchantID()
		// 2017-09-04
		// «The URL to which the payer will be redirected
		// in case of successful creation of Visa QIWI Wallet transaction.
		// URL must be within merchant's site»
		// «URL для переадресации в случае успешного создания транзакции в Visa QIWI Wallet.
		// Ссылка должна вести на сайт провайдера.
		// Если пользователь выбрал на платежной форме способ оплаты,
		// отличный от оплаты с баланса Visa QIWI Wallet,
		// то переадресация на сайт провайдера не выполняется.»
		// Optional, string.
		,'successUrl' => $this->customerReturnRemote()
		// 2017-09-04
		// «"iframe" or empty.
		// This parameter means that hyperlink specified in successUrl / failUrl parameter
		// opens in "iframe" page.»
		// «Флаг, показывающий, что ссылки в параметрах successUrl / failUrl открываются в iframe.
		// Если отсутствует, то считается выключенным.»
		// Optional, string.
		,'target' => ''
		// 2017-09-04
		// «Invoice ID generated by the merchant,
		// corresponds to `bill_id` parameter used to create the bill.»
		// «Идентификатор счета в информационной системе провайдера.
		// Соответствует параметру `bill_id` из запроса на выставление счета.».
		// Required, string.
		,'transaction' => $this->id()
	];}
}